// <auto-generated />
using System;
using HumPsi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumPsi.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumPsi.DataAccess.Entites.ArticlesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HeadlinesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortContent")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortContentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HeadlinesId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("HumPsi.DataAccess.Entites.HeadlinesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Headlines");
                });

            modelBuilder.Entity("HumPsi.DataAccess.Entites.PhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("HumPsi.DataAccess.Entites.SectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleSection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Section");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0537962-9406-496a-a212-314dc18d0c9b"),
                            TitleSection = "Biochemistry"
                        },
                        new
                        {
                            Id = new Guid("dce18de7-942f-4932-8e11-3c898382da00"),
                            TitleSection = "Histology"
                        },
                        new
                        {
                            Id = new Guid("3d9c683d-f36c-4b54-9785-7a0a01157ee5"),
                            TitleSection = "Cardiovascular"
                        },
                        new
                        {
                            Id = new Guid("c89d29a5-07e2-44a5-a3d7-f1792b5a1f93"),
                            TitleSection = "Respiratory"
                        },
                        new
                        {
                            Id = new Guid("071dc2aa-6390-43d6-9de7-6a300089094b"),
                            TitleSection = "Gastrointestinal"
                        },
                        new
                        {
                            Id = new Guid("f76b9295-6e15-4d08-a6ec-51ca700ca6d4"),
                            TitleSection = "Urinary"
                        },
                        new
                        {
                            Id = new Guid("3e549725-45b8-4b79-98fa-5aa1e099671a"),
                            TitleSection = "Reproductive"
                        },
                        new
                        {
                            Id = new Guid("ed5f90ac-910c-4d14-8f5a-2f63ffbcc9bc"),
                            TitleSection = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("6cb5174e-b47a-4e36-bee4-d7a69af58b93"),
                            TitleSection = "Endocrine"
                        },
                        new
                        {
                            Id = new Guid("b6455da2-7c27-4d5a-9cb7-ade0bf471fe0"),
                            TitleSection = "Immunology/Haematology"
                        });
                });

            modelBuilder.Entity("HumPsi.DataAccess.Entites.ArticlesEntity", b =>
                {
                    b.HasOne("HumPsi.DataAccess.Entites.HeadlinesEntity", "Headlines")
                        .WithMany("Articles")
                        .HasForeignKey("HeadlinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Headlines");
                });

            modelBuilder.Entity("HumPsi.DataAccess.Entites.HeadlinesEntity", b =>
                {
                    b.HasOne("HumPsi.DataAccess.Entites.SectionEntity", "Section")
                        .WithMany("Headlines")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("HumPsi.DataAccess.Entites.HeadlinesEntity", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("HumPsi.DataAccess.Entites.SectionEntity", b =>
                {
                    b.Navigation("Headlines");
                });
#pragma warning restore 612, 618
        }
    }
}
